IKQCOMSD1-3553: Add LOCAL_ADDITIONAL_DEPENDENCIES to sanitize kernel headers.
Or it causes random build failure when it is compiling before the kernel headers
are built:
+++
In file included from hardware/moto/sensors/iio_hal/IioSensor.cpp:18:
In file included from external/libcxx/include/memory:629:
In file included from external/libcxx/include/typeinfo:61:
In file included from external/libcxx/include/exception:82:
In file included from external/libcxx/include/cstdlib:86:
In file included from external/libcxx/include/stdlib.h:94:
In file included from bionic/libc/include/stdlib.h:36:
In file included from bionic/libc/include/malloc.h:22:
In file included from external/libcxx/include/stdio.h:108:
In file included from bionic/libc/include/stdio.h:42:
In file included from bionic/libc/include/sys/types.h:36:
kernel/include/linux/types.h:29:9: error: unknown type name '_Bool'
typedef _Bool                   bool;
        ^
kernel/include/linux/types.h:29:17: error: expected unqualified-id
typedef _Bool                   bool;
                                ^
kernel/include/linux/types.h:36:24: error: typedef redefinition with different types ('unsigned long' vs '__uintptr_t' (aka 'unsigned int'))
typedef unsigned long           uintptr_t;
                                ^
bionic/libc/include/stdint.h:71:23: note: previous definition is here
typedef __uintptr_t   uintptr_t;
+++
Change-Id: Ie0ab6b5553434f13e1df7e676b9fa62d0514da4b
Reviewed-on: https://gerrit.mot.com/1010709
SLTApproved: Slta Waiver <sltawvr@motorola.com>
SME-Granted: SME Approvals Granted
Submit-Approved: Jira Key <jirakey@motorola.com>
Tested-by: Jira Key <jirakey@motorola.com>
Reviewed-by: Yin-Jun Chen <a7301c@motorola.com>